// src/data.ts

export type CharacterGenre = 'Action' | 'Fantasy' | 'Romance' | 'Sci-Fi' | 'Comedy' | 'Drama' | 'Dark';
export type HairColor = 'Blonde' | 'Black' | 'Brown' | 'Red' | 'Pink' | 'Blue' | 'Purple' | 'Green' | 'Silver' | 'Orange' | 'Varied';
export type EyeColor = 'Blue' | 'Red' | 'Green' | 'Purple' | 'Yellow' | 'Brown' | 'Pink' | 'Black' | 'Silver' | 'Orange' | 'Heterochromia' | 'Cyan';

export interface CharacterData {
    id: number;
    name: string;
    sourceAnime: string;
    imageUrl: string;
    description: string;
    link?: string;
    themeColor: string;
    genre: CharacterGenre;
    hairColor: HairColor;
    eyeColor: EyeColor; // Nuevo campo
}

export const CHARACTERS: CharacterData[] = [
    // --- LOTE ORIGINAL ---
    { name: "Star Butterfly", sourceAnime: "Star vs The Forces of Evil", imageUrl: "https://iili.io/fEv6RX1.png", description: "Princesa mágica de Mewni, enérgica y caótica.", link: "https://crushon.ai/es/character/04a85c46-6a7e-4257-b8e1-d615a4ff87a6/details?shared=true", themeColor: "#ff0080", genre: "Fantasy", hairColor: "Blonde", eyeColor: "Blue" },
    { name: "Scarlet El Vandimion", sourceAnime: "May I Ask for One Final Thing?", imageUrl: "https://iili.io/f1DfwIj.png", description: "La 'Princesa Perro Loco', resuelve política a puñetazos.", link: "https://crushon.ai/es/character/4581b3d0-3440-4ce2-ba5f-f65ded6a7a11/details?shared=true", themeColor: "#ff2a2a", genre: "Fantasy", hairColor: "Silver", eyeColor: "Blue" },
    { name: "Utena Hiiragi", sourceAnime: "Mahou Shoujo Ni Akogarete", imageUrl: "https://iili.io/f1DCpv1.jpg", description: "Líder villana de Enormita con gustos sádicos.", link: "https://crushon.ai/es/character/1c0580ed-bedd-4a0e-86d3-dc771e703c89/details?shared=true", themeColor: "#8b00ff", genre: "Dark", hairColor: "Purple", eyeColor: "Yellow" },
    { name: "Marcille Donato", sourceAnime: "Dungeon Meshi", imageUrl: "https://iili.io/f1DuSoX.png", description: "Maga elfa experta obligada a comer monstruos.", link: "https://crushon.ai/es/character/9200b5e6-bd0a-4c7b-9a51-313f68f51159/details?shared=true", themeColor: "#a3ff00", genre: "Fantasy", hairColor: "Blonde", eyeColor: "Green" },
    { name: "Maomao", sourceAnime: "The Apothecary Diaries", imageUrl: "https://iili.io/f1DauoB.png", description: "Boticaria excéntrica obsesionada con los venenos.", link: "https://crushon.ai/es/character/f8d14b51-1268-420b-9802-c377db569df9/details?shared=true", themeColor: "#22c55e", genre: "Drama", hairColor: "Green", eyeColor: "Blue" },
    { name: "Mita", sourceAnime: "Mita (OC/Web)", imageUrl: "https://iili.io/f1DlG4t.png", description: "Entidad digital enigmática de origen desconocido.", link: "https://crushon.ai/es/character/630804da-0b6b-42f7-a720-14019361bf77/details?shared=true", themeColor: "#00ffff", genre: "Dark", hairColor: "Blue", eyeColor: "Blue" },
    { name: "Mikadono Sisters", sourceAnime: "Mikadono Sanshimai", imageUrl: "https://iili.io/f1D1cqN.png", description: "Tres hermanas prodigio inútiles en la vida diaria.", link: "https://crushon.ai/es/character/9d29488e-4f47-413b-8e63-09eb6be8897d/details?shared=true", themeColor: "#fbbf24", genre: "Romance", hairColor: "Varied", eyeColor: "Blue" }, // Niko has blue eyes primarily
    { name: "Hitori Gotoh", sourceAnime: "Bocchi The Rock!", imageUrl: "https://iili.io/f1DWdts.jpg", description: "Guitarrista con ansiedad social extrema.", link: "https://crushon.ai/es/character/d33a7610-1b89-4b16-b172-424b79e1bde5/details?shared=true", themeColor: "#f472b6", genre: "Comedy", hairColor: "Pink", eyeColor: "Blue" },
    { name: "Mai Sakurajima", sourceAnime: "Bunny Girl Senpai", imageUrl: "https://iili.io/f1DhCu9.gif", description: "Actriz invisible afectada por el Síndrome de la Pubertad.", link: "https://crushon.ai/es/character/64dafdb6-8009-47e2-ae7b-162d665d3494/details?shared=true", themeColor: "#818cf8", genre: "Romance", hairColor: "Black", eyeColor: "Purple" },
    { name: "Kyouka Uzen", sourceAnime: "Mato Seihei no Slave", imageUrl: "https://iili.io/f1Dj0RS.jpg", description: "Jefa de la 7ª Unidad, esclaviza demonios.", link: "https://crushon.ai/es/character/febe9d67-dbbd-4622-96e5-212fb7342a7e/details?shared=true", themeColor: "#ef4444", genre: "Action", hairColor: "Silver", eyeColor: "Red" },
    { name: "Tino Shade", sourceAnime: "Nageki no Bourei", imageUrl: "https://iili.io/f1DwsEb.jpg", description: "Cazadora talentosa pero cobarde y tímida.", link: "https://crushon.ai/es/character/c6e9fc5e-71be-4d87-b8c7-b02f3716dab7/details?shared=true", themeColor: "#fb7185", genre: "Fantasy", hairColor: "Black", eyeColor: "Blue" },
    { name: "Lucy Heartfilia", sourceAnime: "Fairy Tail", imageUrl: "https://iili.io/f1DO1ON.jpg", description: "Maga de espíritus celestiales de Fairy Tail.", link: "https://crushon.ai/es/character/9734c59c-d0e6-435b-b1c2-793521aca46a/details?shared=true", themeColor: "#facc15", genre: "Fantasy", hairColor: "Blonde", eyeColor: "Brown" },
    { name: "Melty Q. Melromarc", sourceAnime: "Shield Hero", imageUrl: "https://iili.io/f1DvdDN.png", description: "Princesa diplomática, aliada de los semi-humanos.", link: "https://crushon.ai/es/character/9c000e18-3b74-48b6-9eed-37510f50d0b2/details?shared=true", themeColor: "#60a5fa", genre: "Fantasy", hairColor: "Blue", eyeColor: "Blue" },
    { name: "Erika Amano", sourceAnime: "A Couple of Cuckoos", imageUrl: "https://iili.io/f1DvbXS.jpg", description: "Celebridad de internet en un matrimonio arreglado.", link: "https://crushon.ai/es/character/0fb05e26-5d87-42aa-8f3c-97a91118e855/details?shared=true", themeColor: "#f87171", genre: "Romance", hairColor: "Blonde", eyeColor: "Blue" },
    { name: "Nana Hiiragi", sourceAnime: "Talentless Nana", imageUrl: "https://iili.io/f1DgHrX.png", description: "Asesina de 'talentosos' sin poderes reales.", link: "https://crushon.ai/es/character/bf58de3f-17d8-4083-ad67-af5485f332f4/details?shared=true", themeColor: "#ec4899", genre: "Dark", hairColor: "Pink", eyeColor: "Green" },
    { name: "Ais Wallenstein", sourceAnime: "Danmachi", imageUrl: "https://iili.io/f1Dgpuj.png", description: "La poderosa 'Princesa de la Espada'.", link: "https://crushon.ai/es/character/d8d1981f-c7e9-4b1b-974b-31857c78bf67/details?shared=true", themeColor: "#fbbf24", genre: "Fantasy", hairColor: "Blonde", eyeColor: "Yellow" },
    { name: "Alisa Mikhailovna", sourceAnime: "Roshidere", imageUrl: "https://iili.io/f1DrpUX.png", description: "Muestra su afecto hablando en ruso.", link: "https://crushon.ai/es/character/42fee014-fa57-4f9e-b0ae-c8b517497ea6/details?shared=true", themeColor: "#e2e8f0", genre: "Romance", hairColor: "Silver", eyeColor: "Blue" },
    { name: "Mutsumi Yozakura", sourceAnime: "Yozakura Family", imageUrl: "https://iili.io/f1D6OGV.jpg", description: "Líder pacifista de una familia de espías.", link: "https://crushon.ai/es/character/cc94b8bd-7f95-4335-84c3-a02757cbb2fa/details?shared=true", themeColor: "#ffffff", genre: "Action", hairColor: "Blue", eyeColor: "Blue" },
    { name: "Becky Blackbell", sourceAnime: "Spy x Family", imageUrl: "https://iili.io/f1DPKc7.jpg", description: "Amiga de Anya, pequeña fashionista.", link: "https://crushon.ai/es/character/3482e13f-9320-41cd-8644-a819b9a05bd4/details?shared=true", themeColor: "#fbcfe8", genre: "Comedy", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Karane Inda", sourceAnime: "100 Girlfriends", imageUrl: "https://iili.io/f1Diqfp.jpg", description: "Tsundere definitiva con fuerza sobrehumana.", link: "https://crushon.ai/es/character/78511887-a56d-418a-ba86-37daaecf27ab/details?shared=true", themeColor: "#f97316", genre: "Comedy", hairColor: "Orange", eyeColor: "Brown" },
    { name: "Ameri Azazel", sourceAnime: "Iruma-kun", imageUrl: "https://iili.io/f1DLzoG.jpg", description: "Demonio estricta, fan del manga shoujo.", link: "https://crushon.ai/es/character/4d0be4a7-c09b-4cd4-8167-daa8a27994f1/details?shared=true", themeColor: "#ef4444", genre: "Fantasy", hairColor: "Red", eyeColor: "Red" },
    { name: "Kaoruko Waguri", sourceAnime: "Fragrant Flower", imageUrl: "https://iili.io/f1DZ2YN.png", description: "Estudiante de élite enamorada de un delincuente.", link: "https://crushon.ai/es/character/edeff5ee-f3f5-41ff-9606-7128b783fb5d/details?shared=true", themeColor: "#f472b6", genre: "Romance", hairColor: "Black", eyeColor: "Blue" },
    { name: "Cha Hae-In", sourceAnime: "Solo Leveling", imageUrl: "https://iili.io/f1DtRlR.png", description: "Cazadora coreana de rango S.", link: "https://crushon.ai/es/character/837a568a-aa2e-4cfe-9ee0-ae10d2fe8625/details?shared=true", themeColor: "#fbbf24", genre: "Action", hairColor: "Blonde", eyeColor: "Silver" }, // Grayish eyes
    { name: "Momo Ayase", sourceAnime: "Dandadan", imageUrl: "https://iili.io/f1DD7qb.png", description: "Creyente de fantasmas en guerra con aliens.", link: "https://crushon.ai/es/character/77b33d83-8b9d-4efd-b0cf-9b360b6bd53e/details?shared=true", themeColor: "#d946ef", genre: "Action", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Ryoba Aishi", sourceAnime: "Yandere Sim", imageUrl: "https://iili.io/f1DbZKJ.png", description: "La Yandere original, eliminó a todos sus rivales.", link: "https://crushon.ai/es/character/552c2b29-8578-45cd-93f3-9fd8f16b1348/details?shared=true", themeColor: "#7f1d1d", genre: "Dark", hairColor: "Black", eyeColor: "Black" },
    { name: "Megami Saikou", sourceAnime: "Yandere Sim", imageUrl: "https://iili.io/f1Dpodv.png", description: "Heredera absoluta de Saikou Corp.", link: "https://crushon.ai/es/character/4724cde3-c393-4665-99ac-4d1ff56140ed/details?shared=true", themeColor: "#94a3b8", genre: "Dark", hairColor: "Silver", eyeColor: "Silver" },
    { name: "Aqua", sourceAnime: "Konosuba", imageUrl: "https://iili.io/f1boxYN.jpg", description: "Diosa del agua, poderosa pero inútil.", link: "https://crushon.ai/es/character/ccfa2eaa-f4d2-48b6-83a9-aac1f46b5a27/details?shared=true", themeColor: "#06b6d4", genre: "Comedy", hairColor: "Blue", eyeColor: "Blue" },
    { name: "The Quintuplets", sourceAnime: "Go-Toubun", imageUrl: "https://iili.io/f1bJmHG.png", description: "Cinco hermanas unidas por su odio al estudio.", link: "https://crushon.ai/es/character/3fe36111-de82-4590-b53b-91cd7710ec6e/details?shared=true", themeColor: "#f472b6", genre: "Romance", hairColor: "Pink", eyeColor: "Blue" }, 
    { name: "Ai Hoshino", sourceAnime: "Oshi no Ko", imageUrl: "https://iili.io/f1bdw5G.jpg", description: "La idol definitiva con mentiras como amor.", link: "https://crushon.ai/es/character/04215e16-9171-4082-8e47-013cafb3444d/details?shared=true", themeColor: "#d946ef", genre: "Drama", hairColor: "Purple", eyeColor: "Purple" },
    { name: "Suzune Horikita", sourceAnime: "Classroom of Elite", imageUrl: "https://iili.io/f1b2w41.png", description: "Estratega fría que busca la Clase A.", link: "https://crushon.ai/es/character/5d442963-a07c-4676-845a-16ba96f9cd95/details?shared=true", themeColor: "#ef4444", genre: "Drama", hairColor: "Black", eyeColor: "Red" },
    { name: "Torako Koshi", sourceAnime: "Nokotan", imageUrl: "https://iili.io/f1b36Dx.png", description: "Ex-delincuente acosada por una chica ciervo.", link: "https://crushon.ai/es/character/4c015546-d25e-41b4-8f44-c4fccb51fcd7/details?shared=true", themeColor: "#d97706", genre: "Comedy", hairColor: "Blonde", eyeColor: "Purple" },
    { name: "Chisato Nishikigi", sourceAnime: "Lycoris Recoil", imageUrl: "https://iili.io/f1bFlbj.png", description: "Agente de élite pacifista con balas de goma.", link: "https://crushon.ai/es/character/86d5747b-6cf7-477d-b229-a6e431a64d72/details?shared=true", themeColor: "#ef4444", genre: "Action", hairColor: "Blonde", eyeColor: "Red" },
    { name: "Akane Tendo", sourceAnime: "Ranma 1/2", imageUrl: "https://iili.io/f1bKRQR.jpg", description: "Artista marcial y prometida reacia.", link: "https://crushon.ai/es/character/18b5d967-15cb-4d7e-ba8f-d8ab7acf2546/details?shared=true", themeColor: "#1e3a8a", genre: "Comedy", hairColor: "Blue", eyeColor: "Brown" },
    { name: "Ruby Hoshino", sourceAnime: "Oshi no Ko", imageUrl: "https://iili.io/f1bqUqQ.png", description: "Hija de Ai, aspira a restaurar B-Komachi.", link: "https://crushon.ai/es/character/a8552b07-5031-4979-8389-881772a13c12/details?shared=true", themeColor: "#f43f5e", genre: "Drama", hairColor: "Blonde", eyeColor: "Pink" },
    { name: "Nina", sourceAnime: "TCOAAL", imageUrl: "https://iili.io/f1bBSun.jpg", description: "Codependencia tóxica con su hermano.", link: "https://crushon.ai/es/character/ef9a60ab-58c8-4ea8-a88b-00b3fe68a03b/details?shared=true", themeColor: "#4c1d95", genre: "Dark", hairColor: "Purple", eyeColor: "Purple" },

    // --- NUEVAS ADICIONES ---
    { name: "Mihari Oyama", sourceAnime: "Onimai", imageUrl: "https://iili.io/fs3KNVV.md.webp", description: "Científica genio que transformó a su hermano.", link: "https://crushon.ai/es/character/2cc3c135-02a4-4d76-be78-db4967a4a6c8/details?shared=true", themeColor: "#ad2edf", genre: "Comedy", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Emilia", sourceAnime: "Re:Zero", imageUrl: "https://iili.io/fs3qAQ4.md.png", description: "Medio elfa de cabello plateado, candidata real de corazón puro.", link: "https://crushon.ai/es/character/124bad5e-c298-4e23-b2a0-a30f0c90fded/details?shared=true", themeColor: "#a855f7", genre: "Fantasy", hairColor: "Silver", eyeColor: "Purple" },
    { name: "Satou Matsuzaka", sourceAnime: "Happy Sugar Life", imageUrl: "https://iili.io/fs3B7DJ.png", description: "Parece dulce, pero su amor es peligrosamente obsesivo y mortal.", link: "https://crushon.ai/es/character/200e6280-b7d5-4e80-954d-7cdf8502deec/details?shared=true", themeColor: "#f472b6", genre: "Dark", hairColor: "Pink", eyeColor: "Pink" },
    { name: "Erina Nakiri", sourceAnime: "Shokugeki no Soma", imageUrl: "https://iili.io/fs3Caee.md.png", description: "La 'Lengua de Dios'. Altiva, perfeccionista y realeza culinaria.", link: "https://crushon.ai/es/character/64522dae-ffb8-4c7d-b0d2-124641f3c4b9/details?shared=true", themeColor: "#eab308", genre: "Comedy", hairColor: "Blonde", eyeColor: "Purple" },
    { name: "Anna Yamada", sourceAnime: "Bokuyaba", imageUrl: "https://iili.io/fs3nv99.md.png", description: "Modelo popular y glotona que invade la biblioteca escolar.", link: "https://crushon.ai/es/character/fbe51cd1-8e8e-48cf-8e49-3dc3977f61f3/details?shared=true", themeColor: "#06b6d4", genre: "Romance", hairColor: "Black", eyeColor: "Brown" },
    { name: "Stephanie Dola", sourceAnime: "No Game No Life", imageUrl: "https://iili.io/fs3xaet.md.png", description: "Nieta del antiguo rey de Imanity, expresiva y fácil de engañar.", link: "https://crushon.ai/es/character/748c0372-b10c-439d-bcd3-cae0a06bd2a9/details?shared=true", themeColor: "#ec4899", genre: "Fantasy", hairColor: "Red", eyeColor: "Blue" },
    { name: "Katarina Claes", sourceAnime: "Hamefura", imageUrl: "https://iili.io/fs3TRrx.md.png", description: "Villana reencarnada que evita su muerte cultivando vegetales.", link: "https://crushon.ai/es/character/ac7fb7d7-d000-42ba-b234-c52fb3a78efc/details?shared=true", themeColor: "#0ea5e9", genre: "Fantasy", hairColor: "Brown", eyeColor: "Blue" },
    { name: "Chizuru Mizuhara", sourceAnime: "Rent-a-Girlfriend", imageUrl: "https://iili.io/fs3RkhP.md.png", description: "La novia de alquiler perfecta, con un sueño de ser actriz.", link: "https://crushon.ai/es/character/d36f80b1-7805-4cae-bb15-3b2384945d75/details?shared=true", themeColor: "#be123c", genre: "Romance", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Theresia Van Astrea", sourceAnime: "Re:Zero", imageUrl: "https://iili.io/fs337Js.gif", description: "La anterior Santa de la Espada. Fuerte, amable y trágica.", link: "https://crushon.ai/es/character/147877d8-8a5d-4a61-b5e5-884ca90c89a1/details?shared=true", themeColor: "#ef4444", genre: "Fantasy", hairColor: "Red", eyeColor: "Blue" },
    { name: "Kaguya Shinomiya", sourceAnime: "Love is War", imageUrl: "https://iili.io/fs37nVt.md.png", description: "Vicepresidenta genio que hará que te confieses primero.", link: "https://crushon.ai/es/character/e40edd4a-1711-45e9-b2ef-83ddd992fee1/details?shared=true", themeColor: "#dc2626", genre: "Romance", hairColor: "Black", eyeColor: "Red" },
    { name: "Ouka Makuzawa", sourceAnime: "Megami no Cafe Terrace", imageUrl: "https://iili.io/fs3ajP1.md.png", description: "Estudiante de moda y camarera tsundere en Familia Cafe.", link: "https://crushon.ai/es/character/823ebd81-c25d-40b9-868f-575197993cf6/details?shared=true", themeColor: "#ef4444", genre: "Romance", hairColor: "Pink", eyeColor: "Pink" },
    { name: "Mafuyu Kirisu", sourceAnime: "Bokuben", imageUrl: "https://iili.io/fs39GTB.md.png", description: "Maestra estricta con un lado tsundere oculto.", link: "https://crushon.ai/es/character/ad6f31c8-4031-4a23-ac81-506c52b407ee/details?shared=true", themeColor: "#db72a3", genre: "Romance", hairColor: "Pink", eyeColor: "Blue" },
    { name: "Banri Shiunji", sourceAnime: "Shiunji Family", imageUrl: "https://iili.io/fs31os2.md.png", description: "La hermana mayor tsundere de la familia Shiunji.", link: "https://crushon.ai/es/character/9deef3f5-ea8a-42bc-98c3-d6b346649904/details?shared=true", themeColor: "#faa42d", genre: "Romance", hairColor: "Orange", eyeColor: "Purple" },
    { name: "Satoko Kusagakure", sourceAnime: "Nin Koro", imageUrl: "https://iili.io/fs3XlLJ.md.png", description: "Ninja torpe que intenta asesinar a su objetivo sin éxito.", link: "https://crushon.ai/es/character/34780fb3-383c-4c33-ad37-c6e36c9cfcd7/details?shared=true", themeColor: "#eba936", genre: "Comedy", hairColor: "Purple", eyeColor: "Orange" },
    { name: "Ochako Uraraka", sourceAnime: "Boku no Hero", imageUrl: "https://iili.io/fs3hkwF.md.png", description: "Heroína Uravity. Controla la gravedad y trabaja duro por su familia.", link: "https://crushon.ai/es/character/7efdd86c-17fa-4b27-bff5-706b43e3dec8/details?shared=true", themeColor: "#fb7185", genre: "Action", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Shinobu Kocho", sourceAnime: "Kimetsu no Yaiba", imageUrl: "https://iili.io/fs3jbb1.md.png", description: "Pilar del Insecto. Sonrisa amable que oculta una ira profunda.", link: "https://crushon.ai/es/character/1b8722f9-ad1c-42c9-a67e-1f37cbfb90eb/details?shared=true", themeColor: "#a855f7", genre: "Action", hairColor: "Black", eyeColor: "Purple" },
    { name: "Kohaku", sourceAnime: "Dr. Stone", imageUrl: "https://iili.io/fs3N0uI.md.png", description: "Guerrera de la aldea Ishigami con fuerza de leona y vista de águila.", link: "https://crushon.ai/es/character/2a6b6d57-6bd7-48d7-9698-43c5576c3eb6/details?shared=true", themeColor: "#eab308", genre: "Sci-Fi", hairColor: "Blonde", eyeColor: "Blue" },
    { name: "Tohru", sourceAnime: "Maid Dragon", imageUrl: "https://iili.io/fs3O0Ux.md.png", description: "Dragona del caos sirviendo como maid. Ama a Kobayashi.", link: "https://crushon.ai/es/character/aebbc90a-23af-4b7f-a1b2-9468a2b5e44b/details?shared=true", themeColor: "#84cc16", genre: "Comedy", hairColor: "Blonde", eyeColor: "Red" }, // Orage/Red eyes
    { name: "Roxy Migurdia", sourceAnime: "Mushoku Tensei", imageUrl: "https://iili.io/fs3eQCF.md.png", description: "Maga de la raza Migurd. Maestra de agua respetada y adorada.", link: "https://crushon.ai/es/character/e34ccebe-d988-4fd5-b096-9970e650fe46/details?shared=true", themeColor: "#3b82f6", genre: "Fantasy", hairColor: "Blue", eyeColor: "Blue" },
    { name: "Kyoko Kirigiri", sourceAnime: "Danganronpa", imageUrl: "https://iili.io/fs3kYaj.md.png", description: "La Detective Definitiva. Misteriosa, lógica y estoica.", link: "https://crushon.ai/es/character/a2131e4f-cdea-456f-bb23-f752bcdd88cc/details?shared=true", themeColor: "#c084fc", genre: "Dark", hairColor: "Purple", eyeColor: "Purple" },
    { name: "Saki Saki", sourceAnime: "Kanojo Mo Kanojo", imageUrl: "https://iili.io/fs3vGR4.png", description: "La novia principal. Enérgica, celosa pero acepta la poligamia.", link: "https://crushon.ai/es/character/73b13c3d-7d17-4aea-b6ca-a0bb4f3ee6ca/details?shared=true", themeColor: "#fbbf24", genre: "Romance", hairColor: "Red", eyeColor: "Red" },
    { name: "Osaragi", sourceAnime: "Sakamoto Days", imageUrl: "https://iili.io/fs38QC7.md.png", description: "Asesina de la Orden con estilo Goth Lolita y fuerza bruta.", link: "https://crushon.ai/es/character/6c9f5c83-d1b1-4532-bb2b-7fb4e6c219a5/details?shared=true", themeColor: "#18181b", genre: "Action", hairColor: "Black", eyeColor: "Black" },
    { name: "Mabel Pines", sourceAnime: "Gravity Falls", imageUrl: "https://iili.io/fs3Unf9.png", description: "Optimista, amante de los suéteres y el caos adorable.", link: "https://crushon.ai/es/character/05a56e51-3714-4da2-a9d7-df549b12f99b/details?shared=true", themeColor: "#db2777", genre: "Comedy", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Nene Yashiro", sourceAnime: "Hanako-kun", imageUrl: "https://iili.io/fs34IJn.md.png", description: "Asistente humana de Hanako. Romántica y propensa a problemas sobrenaturales.", link: "https://crushon.ai/es/character/13c566e6-c4d3-40b5-9bf6-8ab975696516/details?shared=true", themeColor: "#f472b6", genre: "Fantasy", hairColor: "Silver", eyeColor: "Pink" }, 
    { name: "Diana Cavendish", sourceAnime: "Little Witch Academia", imageUrl: "https://iili.io/fs34vdF.md.png", description: "Bruja de linaje noble. Talentosa, seria y rival de Akko.", link: "https://crushon.ai/es/character/045d2fa3-f1a6-4f45-9473-454709d6a80e/details?shared=true", themeColor: "#bef264", genre: "Fantasy", hairColor: "Blonde", eyeColor: "Blue" },
    { name: "Takagi-san", sourceAnime: "Karakai Jouzu no Takagi-san", imageUrl: "https://iili.io/fs3PdZv.md.png", description: "Maestra de las bromas que disfruta molestando a Nishikata.", link: "https://crushon.ai/es/character/6d8a7e74-2cf9-4e94-b78f-26bf9563530e/details?shared=true", themeColor: "#b45309", genre: "Romance", hairColor: "Brown", eyeColor: "Brown" },
    { name: "Koyuki Chigiri", sourceAnime: "Blue Lock", imageUrl: "https://iili.io/fs3LLR1.md.png", description: "La hermana mayor de Hyoma Chigiri. Amable y comprensiva.", link: "https://crushon.ai/es/character/791b8ff0-80ba-44d3-8d02-745771863ba3/details?shared=true", themeColor: "#f43f5e", genre: "Action", hairColor: "Red", eyeColor: "Red" },
    { name: "Shizuka Mikazuki", sourceAnime: "Zom 100", imageUrl: "https://iili.io/fs3QhXa.md.png", description: "Analista de riesgos pragmática sobreviviendo al apocalipsis zombie.", link: "https://crushon.ai/es/character/6133a979-8546-4605-bb69-8c8de27be125/details?shared=true", themeColor: "#3b82f6", genre: "Action", hairColor: "Purple", eyeColor: "Purple" },
    { name: "Marinette Dupain-Cheng", sourceAnime: "Miraculous Ladybug", imageUrl: "https://iili.io/fs3Z5vI.md.jpg", description: "Diseñadora torpe que protege París como la heroína Ladybug.", link: "https://crushon.ai/es/character/a8736724-aa50-4a9c-b15a-ae7c35139a70/details?shared=true", themeColor: "#dc2626", genre: "Action", hairColor: "Black", eyeColor: "Blue" },
    { name: "Anna Yanami", sourceAnime: "Makeine", imageUrl: "https://iili.io/fs3tDxe.md.png", description: "Heroína perdedora que ama comer y tiene mala suerte en el amor.", link: "https://crushon.ai/es/character/895b7628-8d7c-49dd-b286-a75c8ea42b6a/details?shared=true", themeColor: "#3b82f6", genre: "Romance", hairColor: "Blue", eyeColor: "Blue" },
    { name: "Fern", sourceAnime: "Frieren", imageUrl: "https://iili.io/fs3D87V.md.png", description: "Maga humana discípula de Frieren. Madura y poderosa para su edad.", link: "https://crushon.ai/es/character/457a8f00-aa98-46bf-b3f2-cc40a71abda2/details?shared=true", themeColor: "#7e22ce", genre: "Fantasy", hairColor: "Purple", eyeColor: "Purple" },
    { name: "Alicia Termina Magentano", sourceAnime: "Greatest Estate Developer", imageUrl: "https://iili.io/fsBXH8v.md.png", description: "La reina del reino de Magentano, aliada caótica de Lloyd Frontera.", link: "https://crushon.ai/es/character/00eba01d-4dbe-4df0-b044-cb003e37ca16/details?shared=true", themeColor: "#fbbf24", genre: "Fantasy", hairColor: "Red", eyeColor: "Red" },
    { name: "Lemon Irvine", sourceAnime: "Mashle", imageUrl: "https://iili.io/fs3pFbS.md.png", description: "Maga pesada con una obsesión amorosa intensa por Mash.", link: "https://crushon.ai/es/character/e5796566-3fb6-4b7c-bbbd-379b1e3809ca/details?shared=true", themeColor: "#facc15", genre: "Comedy", hairColor: "Blonde", eyeColor: "Orange" },
    { name: "Marin Kitagawa", sourceAnime: "Sono Bisque Doll", imageUrl: "https://iili.io/fs3pLrb.md.png", description: "Gyaru otaku apasionada por el cosplay y los videojuegos.", link: "https://crushon.ai/es/character/1cd2bdca-67cd-4cfa-adde-afcd5dceb0d0/details?shared=true", themeColor: "#f472b6", genre: "Romance", hairColor: "Blonde", eyeColor: "Pink" }, // Contact lenses usually
    { name: "Iris", sourceAnime: "Fire Force", imageUrl: "https://iili.io/fs3ywuV.md.png", description: "Monja devota que venera a las llamas sagradas.", link: "https://crushon.ai/es/character/1ea384b9-c50d-4375-a882-e3af7b51a78c/details?shared=true", themeColor: "#ea580c", genre: "Action", hairColor: "Blonde", eyeColor: "Blue" },
    { name: "Renee Graves", sourceAnime: "TCOAAL", imageUrl: "https://iili.io/fsFFAVp.md.png", description: "Esposa de Jin Graves, manipuladora y obsesionada con él.", link: "https://crushon.ai/es/character/d160099d-c958-4713-b562-40e92b1e85cf/details?shared=true", themeColor: "#5bd144", genre: "Dark", hairColor: "Black", eyeColor: "Green" },
].map((char, index) => ({
    ...char,
    id: index
}));